baseurl      = "localhost"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  paginate     	  = 10
  enableThemeToggle = true

  # Subtitle for home
  homeSubtitle = "'Mộc Đế 4' - 'Fire Emblem 4: Genealogy of The Holy War'"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  # enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "'Mộc Đế 4' - 'Fire Emblem 4: Genealogy of The Holy War'"
  keywords = "Fire Emblem 4, Genealogy of The Holy War"
  images = [""]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag  	     = "tags"
  series     = "series"

[languages]
  [languages.en]
    title = "Thánh Chiến Truyền Kì"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]
    subtitle  = "A simple theme for Hugo"

    [languages.en.params.logo]
      logoText = "cd /home"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "post"
    name       = "post"
    url        = "/posts"
  [[menu.main]]
    identifier = "about"
    name       = "about"
    url        = "/about/"

